spring.application.name=testProject
spring.datasource.url=jdbc:postgresql://localhost:5433/mydb2
server.port=8189
spring.servlet.context-path=/
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect